import Link from "next/link";
import { Sparkles, ArrowRight, ShieldCheck, Brain, Leaf } from "lucide-react";

export default function HomePage() {
  return (
    <div style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>
      {/* Hero Section */}
      <nav style={{ padding: "20px 40px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
          <div style={{
            width: "38px", height: "38px", borderRadius: "12px",
            background: "var(--gradient-primary)", display: "flex",
            alignItems: "center", justifyContent: "center",
          }}>
            <Sparkles size={20} color="white" />
          </div>
          <span style={{ fontSize: "1.2rem", fontWeight: 700 }}>SkinExpert AI</span>
        </div>
        <div style={{ display: "flex", gap: "12px" }}>
          <Link href="/login" className="glass-button-secondary" style={{ padding: "10px 24px", borderRadius: "10px", textDecoration: "none", fontSize: "0.9rem" }}>
            Log In
          </Link>
          <Link href="/register" className="glass-button" style={{ textDecoration: "none", padding: "10px 24px", fontSize: "0.9rem" }}>
            Get Started
          </Link>
        </div>
      </nav>

      <main style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", textAlign: "center", padding: "40px 20px", maxWidth: "900px", margin: "0 auto" }}>
        <div className="animate-fade-in" style={{ marginBottom: "20px" }}>
          <span style={{
            background: "rgba(168, 85, 247, 0.15)", border: "1px solid rgba(168, 85, 247, 0.3)",
            borderRadius: "100px", padding: "6px 16px", fontSize: "0.8rem", color: "var(--accent-purple)", fontWeight: 500,
          }}>
            ✨ Powered by Google Gemini AI
          </span>
        </div>

        <h1 className="animate-fade-in" style={{ fontSize: "3.5rem", fontWeight: 800, lineHeight: 1.1, marginBottom: "24px" }}>
          Your Personal
          <br />
          <span style={{ background: "var(--gradient-primary)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
            AI Dermatologist
          </span>
        </h1>

        <p className="animate-fade-in" style={{ fontSize: "1.15rem", color: "var(--text-secondary)", maxWidth: "600px", lineHeight: 1.7, marginBottom: "40px" }}>
          Upload a photo, get instant skin analysis, personalized routines adjusted to your local weather, and curated product recommendations—all private and secure.
        </p>

        <div className="animate-fade-in" style={{ display: "flex", gap: "16px", marginBottom: "60px" }}>
          <Link href="/register" className="glass-button" style={{ textDecoration: "none", display: "flex", alignItems: "center", gap: "8px", padding: "14px 32px", fontSize: "1rem" }}>
            Start Free Analysis <ArrowRight size={18} />
          </Link>
        </div>

        {/* Feature Cards */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "20px", width: "100%" }}>
          {[
            { icon: Brain, title: "AI Skin Analysis", desc: "Vision AI analyzes your skin type, concerns, and health score." },
            { icon: ShieldCheck, title: "Privacy First", desc: "FaceDefender™ mask anonymizes your photos before analysis." },
            { icon: Leaf, title: "Smart Routines", desc: "Weather-adaptive morning & evening routines generated by AI." },
          ].map((f, i) => (
            <div key={i} className="glass-card" style={{ padding: "28px", textAlign: "left" }}>
              <f.icon size={28} color="var(--accent-purple)" style={{ marginBottom: "16px" }} />
              <h3 style={{ fontSize: "1.05rem", fontWeight: 600, marginBottom: "8px" }}>{f.title}</h3>
              <p style={{ fontSize: "0.85rem", color: "var(--text-secondary)", lineHeight: 1.6 }}>{f.desc}</p>
            </div>
          ))}
        </div>
      </main>

      {/* Footer Disclaimer */}
      <footer style={{ padding: "20px", textAlign: "center" }}>
        <div className="disclaimer-banner" style={{ maxWidth: "700px", margin: "0 auto" }}>
          ⚕️ SkinExpert AI is a <strong>General Wellness Product</strong>. It does not provide medical diagnosis or treatment. Consult a dermatologist for medical concerns.
        </div>
      </footer>
    </div>
  );
}
